{{- if and .Values.onedev.trustCerts.enabled (not .Values.onedev.trustCerts.existingConfigmapName) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ods.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
  annotations:
    checksum/secret: {{ tpl (toYaml .Values.onedev.trustCerts.path) . | sha256sum }}
data:
  cert.pem: {{ .Values.onedev.trustCerts.path | b64enc }}
{{- end }}
