apiVersion: {{ if .Values.onedev.useStatefulSet }}{{ include "ods.statefulset.apiVersion" . }}{{- else }}{{ include "ods.deployment.apiVersion" . }}{{- end }}
kind: {{ if .Values.onedev.useStatefulSet }}StatefulSet{{- else }}Deployment{{- end }}
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "ods.template-labels" . | nindent 6 }}
  {{- if .Values.onedev.useStatefulSet }}
  serviceName: {{ template "ods.fullname" . }}
  {{- end }}
  {{- if .Values.onedev.updateStrategy}}
  {{- if .Values.onedev.useStatefulSet }}
  updateStrategy:
  {{- else }}
  strategy:
  {{- end }}
    {{- toYaml .Values.onedev.updateStrategy | nindent 4 }}
  {{- end}}
  template:
    metadata:
      labels: {{ include "ods.template-labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
{{- if .Values.onedev.trustCerts.enabled }}
      annotations:
        checksum/secret: {{ tpl (toYaml .Values.onedev.trustCerts.path) . | sha256sum }}
        {{- end }}
        {{- if .Values.podAnnotations }}
{{ tpl (toYaml .Values.podAnnotations) . | indent 8 }}
        {{- end }}
    spec: {{ include "ods.pod" . | nindent 6 }}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (not .Values.onedev.useStatefulSet) }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "ods.fullname" . }}

{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ default "ReadWriteOnce" .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.selector }}
      selector: {{ toYaml .Values.persistence.selector | nindent 8 }}
      {{- end }}
{{- end }}
