{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (not .Values.oneDevServer.useStatefulSet) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ default "" .Values.persistence.storageClassName }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessModes }}
  {{- if .Values.persistence.selector }}
  selector: {{ toYaml .Values.persistence.selector | nindent 8 }}
  {{- end }}
{{- end }}
