apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ods.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.onedev.initSettings.password | b64enc }}
  dbPassword: {{ .Values.database.dbPassword | b64enc }}