{{- $secret_name := "{{.Release.Name}}-mysql" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-mysql

data:
  # try to get the old secret
  # keep in mind, that a dry-run only returns an empty map
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}

  # check, if a secret is already set
  {{- if or (not $old_sec) (not $old_sec.data) }}
  # if not set, then generate a new password
  password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # if set, then use the old value
  password: {{ index $old_sec.data "password" }}
  {{ end }}