{{- if and .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
{{- end }}
{{- if .Values.service.ipFamilies }}
  ipFamilies: {{ toYaml .Values.service.ipFamilies | nindent 4 }}
{{- end }}
  ports:
  - name: http
    port: {{ default "80" .Values.service.ports.http }}
    targetPort: http
    protocol: TCP
{{- if not .Values.service.separateSSHService.enabled }}
  - name: ssh
    port: {{ default "22" .Values.service.ports.ssh }}
    targetPort: ssh
    protocol: TCP
{{- end }}
{{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector: {{ include "ods.template-labels" . | nindent 4 }}
  {{- if .Values.service.topologyKeys }}
  topologyKeys: {{ toYaml .Values.service.topologyKeys | nindent 4 }}
  {{- end }}
{{- end -}}
