{{- if and .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ods.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
{{- end }}
{{- if .Values.service.ipFamilies }}
  ipFamilies: {{ toYaml .Values.service.ipFamilies | nindent 4 }}
{{- end }}
  ports:
  - name: http
    port: {{ default "6610" .Values.service.ports.httpPort }}
    targetPort: http
    protocol: TCP
  - name: git-ssh
    port: {{ default "6611" .Values.service.ports.sshPort }}
    targetPort: git-ssh
    protocol: TCP
  selector: {{ include "ods.template-labels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.topologyKeys }}
  topologyKeys: {{ toYaml .Values.service.topologyKeys | nindent 4 }}
  {{- end }}
{{- end -}}
